### PR TITLE
rebrand and something else

### PR DESCRIPTION
**Pull request by WindowsRefundDay**
Accidentally put `reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\EdgeUpdate" /v "DoNotUpdateToEdgeWithChromium" /t REG_DWORD /d 1` after ` echo Done. Press any key to exit.`

### CODE REVIEW

**Comment by WindowsRefundDay** [comment]
also renamed files

**Comment by jbara2002** [comment]
Are you sure? Melody Script is already in my github
[github.com/jbara2002/melody_windows](https://github.com/jbara2002/melody_windows). 
Edge remover will remain edge remover.

**Comment by WindowsRefundDay** [comment]
yeah, in `README.md` it says 
# Melody 
## Microsoft Edge Remover

**Comment by jbara2002** [comment]
it's leftover.

**Comment by jbara2002** [comment]
i modified now.

**Comment by WindowsRefundDay** [comment]
nice

**Pull request closed without merging**
