### PR TITLE
I added a basic auto system restore point 

### PR DESCRIPTION
**Pull request by WindowsRefundDay**
I added a basic auto system restore point that needs admin permissions to run so I also added a privilege check to check if it is running with admin perms. If it is not running with admin perms then it will `pause` and then `exit`. Really simple but I thought it could help :)

### CODE REVIEW

**Comment by WindowsRefundDay** [comment]
I also made it when the script finishes, it clears the cmd and to press any key to finish script.

**Comment by jbara2002** [comment]
Why are you putted
__EdgeWebView\Application\%edge_chromium_package_version%\Installer\setup.exe --uninstall --force-uninstall --msedgewebview --system-level --verbose-logging__?
I can understand the ideea of the edge removal, but for Windows OS, i don't have a 3rd Party WebView. 
The ideea of the automatic restore point creation is good, i will apply to Defender Remover, because it helps to restore if is the part of the Remover.

**Comment by jbara2002** [comment]
So the explication on that. The EdgeWebView is needed for some apps where a sign in window is showed with opening the browser. If this is removed, an ancient IE format window it will be shown. (example adding your mail address to 3rd mail app (adding an GMAIL address to Thunderbird) or connecting to the Adobe CC Applications with your account.. or in Visual Studio with the github account.

**Comment by WindowsRefundDay** [comment]
oh ok thanks for clarifying! im making a new pull request because of a accident in the code which will be explained in it.

**Pull request merged**
